# generated by datamodel-codegen:
#   filename:  OMSA.yaml
#   timestamp: 2026-03-19T12:18:37+00:00

from __future__ import annotations

from typing import Any, Literal

from pydantic import (
    AnyUrl,
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    confloat,
    conint,
    constr,
)


class Subscriber(BaseModel):
    successUri: AnyUrl | None = None
    inProgressUri: AnyUrl | None = None
    failedUri: AnyUrl | None = None


class ConfClasses(BaseModel):
    conformsTo: list[str]


class BasePointItem(RootModel[confloat(ge=0.0)]):
    root: confloat(ge=0.0)


class BasePoint(RootModel[list[BasePointItem]]):
    root: list[BasePointItem] = Field(..., max_length=2, min_length=2)


class GeojsonPoint(BaseModel):
    coordinates: BasePoint


class GeojsonLine(BaseModel):
    coordinates: list[BasePoint]


class GeojsonPolygon(BaseModel):
    coordinates: list[list[BasePoint]]


class GeojsonMultiPolygon(BaseModel):
    coordinates: list[list[list[BasePoint]]]


class Properties(BaseModel):
    name: str | None = None


class Crs(BaseModel):
    type: str | None = None
    properties: Properties | None = None


class TypeOfTravelDocument(
    RootModel[
        Literal[
            'LINK',
            'BARCODE',
            'QRCODE',
            'AZTECCODE',
            'AXA_EKEY_OTP',
            'BLUETOOTH',
            'NFC',
            'PHYSICAL_KEY',
            'EXTERNAL_CARD',
            'OTHER',
        ]
    ]
):
    root: Literal[
        'LINK',
        'BARCODE',
        'QRCODE',
        'AZTECCODE',
        'AXA_EKEY_OTP',
        'BLUETOOTH',
        'NFC',
        'PHYSICAL_KEY',
        'EXTERNAL_CARD',
        'OTHER',
    ] = Field(..., description='how this type is implemented?<br>')


class Mode(
    RootModel[
        Literal[
            'AIR',
            'BUS',
            'TROLLEYBUS',
            'TRAM',
            'COACH',
            'RAIL',
            'INTERCITYRAIL',
            'URBANRAIL',
            'METRO',
            'WATER',
            'CABLEWAY',
            'FUNICULAR',
            'TAXI',
            'SELFDRIVE',
            'FOOT',
            'BICYCLE',
            'MOTORCYCLE',
            'CAR',
            'SHUTTLE',
            'OTHER',
            'PARKING',
            'MOPED',
            'STEP',
            'FERRY',
        ]
    ]
):
    root: Literal[
        'AIR',
        'BUS',
        'TROLLEYBUS',
        'TRAM',
        'COACH',
        'RAIL',
        'INTERCITYRAIL',
        'URBANRAIL',
        'METRO',
        'WATER',
        'CABLEWAY',
        'FUNICULAR',
        'TAXI',
        'SELFDRIVE',
        'FOOT',
        'BICYCLE',
        'MOTORCYCLE',
        'CAR',
        'SHUTTLE',
        'OTHER',
        'PARKING',
        'MOPED',
        'STEP',
        'FERRY',
    ] = Field(
        ...,
        description='These classes are taken from the NeTeX standard, but ALL and UNKNOWN are removed. On the other hand OTHER and PARKING are added.',
    )


class ClassOfUse(
    RootModel[
        Literal[
            'FIRST_CLASS',
            'SECOND_CLASS',
            'THIRD_CLASS',
            'ECONOMY_CLASS',
            'BUSINESS_CLASS',
            'TURISTA',
            'PREFERENTE',
            'PREMIUM_CLASS',
            'ANY',
            'UNKNOWN',
        ]
    ]
):
    root: Literal[
        'FIRST_CLASS',
        'SECOND_CLASS',
        'THIRD_CLASS',
        'ECONOMY_CLASS',
        'BUSINESS_CLASS',
        'TURISTA',
        'PREFERENTE',
        'PREMIUM_CLASS',
        'ANY',
        'UNKNOWN',
    ] = Field(
        ...,
        description='A classification of fare and other service classes by category of user entitled to use them.',
    )


class PackageStatus(
    RootModel[
        Literal[
            'OFFERED',
            'SELECTED',
            'PENDING',
            'CONFIRMED',
            'RELEASED',
            'EXPIRED',
            'CANCELLED',
            'REFUND_CLAIMED',
            'REFUNDED',
            'STARTED',
            'ENDED',
        ]
    ]
):
    root: Literal[
        'OFFERED',
        'SELECTED',
        'PENDING',
        'CONFIRMED',
        'RELEASED',
        'EXPIRED',
        'CANCELLED',
        'REFUND_CLAIMED',
        'REFUNDED',
        'STARTED',
        'ENDED',
    ] = Field(
        ...,
        description="The life-cycle state of the package (from NEW to ENDED)<br> _OFFERED_ the package is offered<br> _SELECTED_ the package is selected to modify<br> _PENDING_ the purchase of the package is not confirmed (the end user has shown intentions to purchase this offer), must be finalized with the package-confirm operation<br> _CONFIRMED_ a finalized package ('purchased'). Both parties agreed to deliver services in return of payment<br> _CANCELLED_ the package is cancelled after it is purchased. The agreement will specify whether there is a refund, or under which conditions<br> _EXPIRED_ the MP didn't respond on time, the package offer has been expired<br> _STARTED_ the package is started, the <u>trip execution</u> module is needed now to manage the execution of the package<br> _ENDED_ the package has ended, the trip has been executed<br> _RELEASED_ for internal archiving, the package has not been purchased.<br>",
    )


class LegState(
    RootModel[
        Literal[
            'NOT_started',
            'PREPARING',
            'PREPARED',
            'IN_USE',
            'PAUSED',
            'ENDED',
            'ISSUE_REPORTED',
            'CANCELLED',
            'ABENDED',
        ]
    ]
):
    root: Literal[
        'NOT_started',
        'PREPARING',
        'PREPARED',
        'IN_USE',
        'PAUSED',
        'ENDED',
        'ISSUE_REPORTED',
        'CANCELLED',
        'ABENDED',
    ] = Field(
        ...,
        description="status of a leg<br> _NOT_STARTED_ the leg is not started, initial state<br> _PREPARING_ the _PREPARE_ operation has been received<br> _PREPARED_ the leg is ready to use<br> _IN_USE_ the travelers are on their way<br> _PAUSED_ the asset is paused<br> _ENDED_ the travelers have arrived at their destination<br> _ISSUE_REPORTED_ due to an issue, there is (temporarily) no progress to report, when the issue isn't solved, this is a final state<br> _CANCELLED_ the leg has been cancelled, before execution<br> _ABENDED_ the leg is abnormally ended (e.g. due to an issue)",
    )


class Country(RootModel[constr(pattern=r'[A-Z]{2}', min_length=2, max_length=2)]):
    root: constr(pattern=r'[A-Z]{2}', min_length=2, max_length=2) = Field(
        ..., description='two-letter country codes according to ISO 3166-1'
    )


class CurrencyCode(
    RootModel[constr(pattern=r'[a-zA-Z]{3}', min_length=3, max_length=3)]
):
    root: constr(pattern=r'[a-zA-Z]{3}', min_length=3, max_length=3) = Field(
        ..., description='ISO 4217 currency code'
    )


class CustomProperties(RootModel[dict[str, Any]]):
    root: dict[str, Any]


class PaymentCategory(
    RootModel[
        Literal[
            'ALL',
            'DAMAGE',
            'LOSS',
            'STOLEN',
            'EXTRA_USAGE',
            'REFUND',
            'REBATE',
            'REIMBURSEMENT',
            'FINE',
            'OTHER_ASSET_USED',
            'CREDIT',
            'VOUCHER',
            'DEPOSIT',
            'OTHER',
            'FARE',
            'FEE',
        ]
    ]
):
    root: Literal[
        'ALL',
        'DAMAGE',
        'LOSS',
        'STOLEN',
        'EXTRA_USAGE',
        'REFUND',
        'REBATE',
        'REIMBURSEMENT',
        'FINE',
        'OTHER_ASSET_USED',
        'CREDIT',
        'VOUCHER',
        'DEPOSIT',
        'OTHER',
        'FARE',
        'FEE',
    ] = Field(
        ...,
        description='The category of the journalled item <br> _ALL_ - for filtering purposes only<br>\n<h2>TO initiated payments </h2> To request these payments, use the notifications, send a notification containing the payment confirmation.<br> _DEPOSIT_ - a deposit, to refund, use _REFUND_<br> _DAMAGE_ - extra costs that must be paid by the MP due to damage to the asset or ancillaries<br> _LOSS_ - extra costs that must be paid by the MP due to loss of asset or ancillaries<br> _STOLEN_ - the asset (and ancillaries) are stolen and should be paid for<br> _EXTRA_USAGE_ - the asset is paid for in advance, additional usage must be paid for (can also be a refund when used less! The amount should be negative in that case)<br> _FINE_ - a fine that arrived later on<br> _OTHER_ASSET_USED_ - additional costs for a replaced asset<br> _FARE_ - the normal costs of the purchased and executed leg(s)<br> _OTHER_ - unspecified<br>\n_CREDIT_ - generic CREDIT, e.g. for kick-backs <br> _VOUCHER_ - part of the fare that is covered by a voucher (no need to pay)<br> _REFUND_ - refund of the deposit or upfront paid fare<br> _REBATE_ - (partial) rebate of the fare<br> _REIMBURSEMENT_ - reimbursement of the fare<br>',
    )


class DataType(RootModel[str | Literal['map', 'vector', 'coverage']]):
    root: str | Literal['map', 'vector', 'coverage']


class JobControlOptions(RootModel[Literal['sync-execute', 'async-execute', 'dismiss']]):
    root: Literal['sync-execute', 'async-execute', 'dismiss']


class Metadata2(BaseModel):
    role: str | None = None
    title: str | None = None
    lang: str | None = None
    value: str | dict[str, Any] | None = None


class Date(RootModel[str]):
    root: str = Field(
        ...,
        description='https://www.rfc-editor.org/rfc/rfc3339#section-5.6, full-date (2019-10-12)',
    )


class DateTime(RootModel[AwareDatetime]):
    root: AwareDatetime = Field(
        ...,
        description='https://www.rfc-editor.org/rfc/rfc3339#section-5.6, date-time (2019-10-12T07:20:50.52Z)',
    )


class Day(RootModel[Literal['MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN']]):
    root: Literal['MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN']


class Float(RootModel[confloat(ge=0.0)]):
    root: confloat(ge=0.0) = Field(
        ..., description='the travelled distance. Only if applicable.'
    )


class HttpDate(RootModel[str]):
    root: str = Field(..., description='A HTTP date string')


class LongInt(RootModel[conint(ge=0)]):
    root: conint(ge=0) = Field(
        0, description='long number, for distances etc. (>1.000)'
    )


class LongString(RootModel[constr(max_length=10000)]):
    root: constr(max_length=10000) = Field(
        ..., description='long string, memos etc (length 0-10.000)'
    )


class NormalInt(RootModel[conint(ge=0, le=1000)]):
    root: conint(ge=0, le=1000) = Field(
        0, description='default length for an integer (0-1000)'
    )


class NormalString(RootModel[constr(max_length=200)]):
    root: constr(max_length=200) = Field(
        ..., description='default string, full names etc (length 0-200)'
    )


class ShortInt(RootModel[conint(ge=0, le=100)]):
    root: conint(ge=0, le=100) = Field(0, description='a bit short integer (0-100)')


class ShortString(RootModel[constr(max_length=75)]):
    root: constr(max_length=75) = Field(
        ..., description='short string, display names (length 0-75)'
    )


class TinyInt(RootModel[conint(ge=0, le=10)]):
    root: conint(ge=0, le=10) = Field(0, description='for really small numbers (0-10)')


class TinyString(RootModel[constr(max_length=10)]):
    root: constr(max_length=10) = Field(
        ..., description='real short string, codes (length 0-10)'
    )


class Url(RootModel[AnyUrl]):
    root: AnyUrl = Field(..., description='valid URL')


class Uuid(RootModel[str]):
    root: str = Field(
        ...,
        description='https://en.wikipedia.org/wiki/Universally_unique_identifier see also https://www.ietf.org/rfc/rfc4122.txt (ae76f51c-a1a6-46af-b9ab-8233564adcae)',
    )


class RefundOptionInput(BaseModel):
    type: constr(pattern=r'^(claim_refund_option|confirm_refund_option)$')
    optionId: Uuid | None = None


class TravelDocument(BaseModel):
    startvalidity: DateTime
    endvalidity: DateTime
    travelDocumentType: TypeOfTravelDocument


class CommercialProfile(BaseModel):
    id: ShortString | None = None
    type: constr(pattern=r'^(commercial_profile)$')
    code: ShortString | None = None
    name: NormalString | None = None


class EntitlementGiven(BaseModel):
    id: ShortString | None = Field(
        None,
        description='a unique ID for this usage. Especially required when it is a USER PROFILE or an INDIVIDUAL TRAVELLER. Other concepts might refer to this ID.',
    )
    type: constr(pattern=r'^(entitlement)$')
    entitlementType: NormalString


class TemporalParameter(BaseModel):
    type: constr(pattern=r'^(temporal)$')
    startTime: DateTime | None = None
    endTime: DateTime | None = None
    duration: NormalInt | None = Field(default_factory=lambda: NormalInt(0))
    dayType: Day | None = None


class OnboardStay(BaseModel):
    type: constr(pattern=r'^(onboard_stay)$')
    description: LongString | None = None
    classOfUse: ClassOfUse | None = None
    permission: bool | None = None
    duration: ShortString | None = None


class Accommodation(BaseModel):
    type: constr(pattern=r'^(accommodation)$') | None = None
    description: LongString | None = None
    classOfUse: ClassOfUse | None = None
    name: ShortString | None = None
    gender: Literal['M', 'F', 'X', 'U'] | None = None
    berthType: Literal['SLEEPER', 'COUCHETTE', 'SEAT', 'OTHER'] | None = None
    nuisanceFacility: list[ShortString] | None = None


class DistributionParameter(BaseModel):
    type: constr(pattern=r'^(distribution)$')
    fulfilmentMethod: NormalString | None = None
    distributionChannel: NormalString | None = None


class OrganisationalParameter(BaseModel):
    id: ShortString
    type: constr(pattern=r'^(organisational)$')
    name: NormalString | None = None
    legalName: NormalString | None = None


class LicenseType(BaseModel):
    type: constr(pattern=r'^(license_type)$')
    modes: list[Mode] | None = None
    licenseCode: ShortString | None = Field(
        None,
        description="in most countries a driver license has also a code. As TO you can exactly verify, based on this code if the license allows to operate it's assets, if the assetType too generic.",
    )
    issuingCountry: Country | None = None
    customFields: CustomProperties | None = None


class Guarantee(BaseModel):
    id: ShortString | None = None
    type: (
        Literal[
            'ALTERNATIVE_JOURNEY',
            'HOME_LEG',
            'RETURN_TO_ORIGIN',
            'ON_TIME_TRAVEL',
            'TRIP_ON_TIME',
            'FACILITIES_AVAILABLE',
            'MOBILITY_ACCOMODATION',
            'MOBILITY_ASSISTANCE',
            'PASSENGER_SUPPORT',
            'DISRUPTION_INFORMATION',
            'REDRESS_INFORMATION',
            'BEST_FARE_INFORMATION',
            'GENERAL_TRAVEL',
            'MEDIA_REPLACEMENT',
            'REFUND_UNUSED_ANCILLARIES',
            'REFUND_WHEN_CANCELLED',
        ]
        | None
    ) = Field(None, description='default string, full names etc (length 0-200)')


class AmountOfMoney(BaseModel):
    amount: float = Field(
        ...,
        description='This should be in the base unit as defined by the ISO 4217 currency code with the appropriate number of decimal places and omitting the currency symbol. e.g. if the price is in US Dollars the price would be 9.95. This is inclusive VAT',
    )
    taxPercentageUsed: Float | None = Field(
        None, description='value added tax rate (percentage of amount)'
    )
    currencyCode: CurrencyCode | None = None
    vatCountryCode: Country | None = None


class BinaryTicket(TravelDocument):
    type: Literal['binaryTicket']
    contentType: str = Field(..., description='the media type (IANA)')
    base64: LongString = Field(..., description='base 64 binary data')
    version: TinyString | None = None


class ExternalTicket(TravelDocument):
    type: Literal['externalTicket']


class ExternalReference(RootModel[NormalString]):
    root: NormalString


class OrganisationReference(BaseModel):
    organisationId: NormalString
    name: NormalString | None = None


class PlaceReference(BaseModel):
    placeId: constr(pattern=r'^(GPS:|NSR:StopPlace:|P:|KOL:)', max_length=200) = Field(
        ...,
        description="this string references to information that can be found in the `data sources`. Enlist all prefixes (=rel) from the /collections/datasources/items that apply to a place/location. Default it matches already with 'GPS' (no entry required in the datasources). In case of a custom place (like home address), you can use the 'P:' prefix and add the address to the **placeDefinitions** list of the request.",
    )
    name: NormalString | None = None


class CustomerReference(RootModel[NormalString]):
    root: NormalString


class TravellerReference(RootModel[NormalString]):
    root: NormalString


class UserProfileReference(RootModel[NormalString]):
    root: NormalString


class ProductReference(BaseModel):
    productId: NormalString
    name: NormalString


class OfferReference(RootModel[NormalString]):
    root: NormalString


class PackageReference(RootModel[NormalString]):
    root: NormalString


class LegReference(RootModel[NormalString]):
    root: NormalString


class LineReference(RootModel[NormalString]):
    root: NormalString


class ZoneReference(BaseModel):
    zoneId: NormalString
    name: NormalString | None = None


class AssetReference(RootModel[NormalString]):
    root: NormalString


class AncillaryReference(BaseModel):
    ancillaryId: NormalString
    name: NormalString | None = None


class EquipmentReference(BaseModel):
    equipmentId: NormalString
    name: NormalString | None = None


class ServiceJourneyReference(RootModel[NormalString]):
    root: NormalString


class UserNeedReference(BaseModel):
    id: NormalString
    name: NormalString | None = None


class Link(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    rel: str = Field(
        ...,
        description="the action that can be performed OR part of the URI allowed values include the 'processId's, prefixes for the referenced data sources, prefixes for deeplinks ('apple' and 'android'), OGC compliant ones (alternative, next, etc)",
    )
    href: Url
    type: ShortString | None = Field(
        None,
        description='allowed values are described by IANA, ("application/geo+json")',
    )
    method: Literal['POST', 'GET', 'PUT', 'DELETE', 'PATCH'] | None = Field(
        None, description='to indicate the http method.'
    )
    description: str | None = Field(
        None, description='the description of the external data source'
    )
    body: dict[str, Any] | None = Field(
        None, description='the (prefilled) body for the request'
    )
    headers: dict[str, str] | None = None
    isMandatory: bool | None = Field(
        None, description='is this link informative, or must it be used?'
    )
    hash: str | None = Field(
        None,
        description="to validate that the content of the link hasn't been changed.",
    )
    validity: TemporalParameter | None = None


class SelectOffersInput(BaseModel):
    offerIds: list[OfferReference]
    type: constr(pattern=r'^(select_offers)')
    timestamp: DateTime | None = Field(None, description='timestamp of request')


class PackageInput(BaseModel):
    packageId: PackageReference
    type: constr(pattern=r'^(package)')
    timestamp: DateTime | None = Field(None, description='timestamp of request')


class LegInput(PackageInput):
    offerId: OfferReference | None = None
    legId: LegReference
    type: constr(pattern=r'^(leg)')
    location: PlaceReference | None = None


class RemoveTravellerInput(BaseModel):
    type: constr(pattern=r'^(traveller)$')
    travellerId: TravellerReference
    packageId: PackageReference


class AssetInput(LegInput):
    type: constr(pattern=r'^(asset)$')
    assetId: AssetReference
    replaceAssetId: AssetReference | None = None


class AncillaryInput(LegInput):
    type: constr(pattern=r'^(ancillary)$')
    ancillaryId: AncillaryReference
    replaceAncillaryId: AncillaryReference | None = None


class PurchaseOffersInput(SelectOffersInput):
    type: constr(pattern=r'^(purchase_offers)$')


class ExtendExpiryTimeInput(PackageInput):
    type: constr(pattern=r'^(extend_expiry_time)$')
    extensionReason: (
        constr(pattern=r'^(purchase_pending|payment_pending|other)$') | None
    ) = Field(
        None,
        description='in case operation is EXTEND_EXPIRY_TIME, the reason for extension must be supplied here.<br> _PURCHASE_PENDING_ - The internal purchase process on the MP side is not yet finished<br> _PAYMENT_PENDING_ - The customer is in the payment process<br> _OTHER_ - unspecified',
    )


class Product(BaseModel):
    type: constr(pattern=r'^(product)$') | None = None
    productId: ProductReference | None = None
    productName: NormalString | None = None
    guarantees: list[Guarantee] | None = Field(
        None,
        description='references to products that are contained in this product (to facilitate e.g. travel through) If his combined product is named in a package, the referenced packages must be enlisted as well.',
    )


class TripPatternItem(BaseModel):
    serviceJourney: ServiceJourneyReference | None = None
    date: Date | None = None
    from_: PlaceReference | None = Field(None, alias='from')
    to: PlaceReference | None = None


class TripPattern(RootModel[list[TripPatternItem]]):
    root: list[TripPatternItem]


class TravelSpecification(BaseModel):
    from_: PlaceReference | None = Field(
        None,
        alias='from',
        description="use an ID contained in the **placeDefinitions** field, or from an external source, when using coordinates, please use the prefix 'gps:'",
    )
    via: list[PlaceReference] | None = Field(
        None,
        description="use an ID contained in the **placeDefinitions** field, or from an external source, when using coordinates, please use the prefix 'gps:'",
        max_length=3,
        min_length=0,
    )
    to: PlaceReference | None = Field(
        None,
        description="use an ID contained in the **placeDefinitions** field, or from an external source, when using coordinates, please use the prefix 'gps:'",
    )
    startTime: DateTime | None = Field(
        None,
        description='The intended departure time. If left out and no endTime is set, the current time should be assumed. If only the arrival time is specified, this is an implicit request for a guaranteed arrival at that time.',
    )
    endTime: DateTime | None = Field(
        None,
        description='The intended arrival time, at the `to place`. When the **startTime** is not set, and **endTime** is set, it is an implicit request for an arrival time guarantee.',
    )


class PostalAddress(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    placeId: PlaceReference | None = None
    addressLine1: LongString = Field(
        ...,
        description='contains street, housenumber & additions example street 18, 2nd floor, 18-B33',
    )
    addressLine2: LongString = Field(
        ...,
        description='city or town, principal subdivision such as province, state or county Smallcity, Pinetree county',
    )
    street: NormalString | None = Field(
        None, description='street, consistent with addressLine1'
    )
    houseNumber: NormalInt | None = Field(
        default_factory=lambda: NormalInt(0),
        description='house number, consistent with addressLine1',
    )
    houseNumberAddition: TinyString | None = Field(
        None,
        description="the additional part of the house number (f.x. 13bis, where 'bis' is the additional part), consistent with addressLine1",
    )
    postalCode: ShortString | None = Field(
        None, description='the postal code, whenever available'
    )
    city: ShortString | None = Field(
        None, description='specified city or town, consistent with addressLine2'
    )
    province: ShortString | None = Field(
        None, description='province or region, consistent with addressLine2'
    )
    state: ShortString | None = Field(
        None, description='state, consistent with addressLine2'
    )
    country: Country | None = None
    additionalInfo: LongString | None = Field(
        None,
        description='additional information to find the address (f.x. just around the corner)',
    )


class TravellingAsset(BaseModel):
    type: constr(pattern=r'^(asset)$')
    id: AssetReference


class EquipmentParameter(BaseModel):
    type: constr(pattern=r'^(equipment)$')
    id: EquipmentReference | None = None
    name: ShortString | None = None
    description: LongString | None = None
    infoLink: Url | None = None
    image: Url | None = None


class SpotReservationParameter(BaseModel):
    type: constr(pattern=r'^(spot_reservation)$')
    spotType: Literal['VEHICLE_SPOT', 'PASSENGER_SPOT', 'LUGGAGE_SPOT']
    deck: ExternalReference | None = None
    space: ExternalReference | None = None
    spot: ExternalReference
    width: float | None = None
    length: float | None = None
    height: float | None = None
    fuel: str | None = None
    weight: str | None = None
    mode: Mode | None = None


class NetworkParameter(BaseModel):
    type: constr(pattern=r'^(network)$')
    location: PlaceReference | None = None
    line: LineReference | None = None
    zones: list[ZoneReference] | None = None


class RoutingParameter(BaseModel):
    type: constr(pattern=r'^(routing)$')
    journeyPattern: list[ExternalReference]


class ServiceParameter(BaseModel):
    type: constr(pattern=r'^(service)$')
    product: ProductReference | None = None
    asset: AssetReference | None = None
    serviceJourney: ServiceJourneyReference | None = None
    userNeeds: list[UserNeedReference] | None = None
    class_: ClassOfUse | None = Field(None, alias='class')
    onboardStay: list[OnboardStay] | None = None
    accommodations: list[Accommodation] | None = None


class CancellationParameter(BaseModel):
    type: constr(pattern=r'^(cancel)$')
    cancellationAllowed: bool | None = Field(
        None, description='is it possible to cancel this package?'
    )
    cancellationFee: AmountOfMoney | None = Field(
        None,
        description='amount of money you have to pay when you cancel this purchased package',
    )
    cancellationFeePercentage: confloat(ge=0.0, le=100.0) | None = Field(
        None,
        description='percentage of the offered price you have to pay when you cancel this purchased package',
    )


class PurchaseParameter(BaseModel):
    type: constr(pattern=r'^(purchase)$')
    maximumPeriodBeforeDeparture: LongInt | None = Field(
        default_factory=lambda: LongInt(0),
        description='Maximum time in minutes that an asset can be reserved before a rental begins.',
    )
    requiredLicenseTypes: list[LicenseType] | None = Field(
        None,
        description='ONE of these licenses is required to operate the asset',
        max_length=5,
    )


class CardType(BaseModel):
    id: ShortString = Field(
        ..., description='external reference to address the card used.'
    )
    type: constr(pattern=r'^(card_type)$')
    cardCategory: (
        Literal['DISCOUNT', 'TRAVEL', 'BANK', 'CREDIT', 'ID', 'PASSPORT', 'OTHER']
        | None
    ) = Field(
        None,
        description="The category of card<br> DISCOUNT - discount card, can be applied in the purchase process to get rebate<br> TRAVEL - (external) travel card, possibly paid for in other context, but also monthly, weekly or day-cards<br> BANK - bank card<br> CREDIT - credit card<br> ID - identification card, like an ID card<br> PASSPORT - passport to identify yourself<br> OTHER - unspecified, use 'subCategory' to specify the category of card",
    )
    subCategory: ShortString | None = Field(
        None,
        description='For use in case of OTHER. Can be used in bilateral agreements.',
    )
    relatedProduct: ProductReference | None = None
    transportOrganisations: list[OrganisationReference] | None = Field(
        None,
        description='references to accepting parties, only if applicable',
        max_length=15,
    )
    customFields: CustomProperties | None = None


class License(BaseModel):
    type: constr(pattern=r'^(license)$')
    licenseType: LicenseType | None = None
    licenseNumber: ShortString | None = None
    endValidity: Date | None = None


class TravelDocument1(BaseModel):
    id: NormalString | None = None
    properties: ExternalTicket | BinaryTicket | None = Field(None, discriminator='type')
    links: list[Link] | None = None


class TravelDocumentCollection(BaseModel):
    type: constr(pattern=r'^(TravelDocumentCollection)$')
    travelDocuments: list[TravelDocument1] | None = None
    numberMatched: int | None = None
    numberReturned: int | None = None
    links: list[Link] | None = Field(
        None,
        description='actions that can be performed on this package, but also alternative (rel=alternative+1, alternative+2) offers or references to other resources In case it is an alternative, specify clearly in the description what the financial consequences are.',
    )


class Ancillary(AncillaryReference):
    type: constr(pattern=r'^(ancillary)$') | None = None
    price: AmountOfMoney | None = Field(
        None, description='The additional cost of this ancillary if selected.'
    )
    description: str | None = Field(
        None,
        description="A user-friendly description of the ancillary (e.g. 'Reserved seat for bike').",
    )
    available: int | None = Field(
        None,
        description='Number of items available in stock (inventory). Useful for creating urgency in GUI.',
    )
    links: list[Link] | None = None


class Seat(BaseModel):
    type: constr(pattern=r'^(seat)$') | None = None
    id: ExternalReference | None = None
    deck: ShortString | None = None
    space: ShortString | None = None
    row: ShortInt | None = Field(default_factory=lambda: ShortInt(0))
    seatNumber: ShortInt | None = Field(default_factory=lambda: ShortInt(0))
    facing: Literal['FRONT', 'REAR', 'LEFT', 'RIGHT', 'OTHER'] | None = None
    byWindow: bool | None = None
    legSpace: ShortInt | None = Field(
        default_factory=lambda: ShortInt(0), description='in cm'
    )
    byAisle: bool | None = None
    hasArmRest: bool | None = None
    hasTray: bool | None = None
    hasAirco: bool | None = None
    hasEnergySupply: bool | None = None
    hasLight: bool | None = None


class Asset(BaseModel):
    type: constr(pattern=r'^(asset)$') | None = None
    id: AssetReference | None = Field(
        None,
        description='Identifier of an asset. Can be an external reference, but also a (internal) ID',
    )
    visualId: ShortString | None = Field(
        None, description='for instance, a license plate or seat number.'
    )
    product: ProductReference | None = None
    mode: Mode | None = None
    subMode: NormalString | None = Field(
        None,
        description="a more precise classification of the asset, like 'cargo bike', 'public bus', 'coach bus', 'office bus', 'water taxi',  'segway'. This is mandatory when using 'OTHER' as class.",
    )
    equipment: list[EquipmentReference] | None = Field(
        None, description='list of external references', max_length=100
    )


class PlaceDefinitions(BaseModel):
    placeDefinitions: list[PostalAddress] | None = Field(
        None,
        description='Places that are not specified in an external data source (like a home address)',
        max_length=3,
        min_length=0,
    )


class FinancialDetail(BaseModel):
    amount: AmountOfMoney | None = None
    package: PackageReference | None = None
    offer: OfferReference | None = None
    leg: LegReference | None = None
    category: PaymentCategory | None = None
    expirationDate: DateTime | None = None
    customFields: CustomProperties | None = None


class Error(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    errorcode: TinyInt = Field(..., description='The specific error code')
    type: TinyString | None = Field(
        None, description='The category of this type of error.'
    )
    title: ShortString = Field(
        ...,
        description='A short, human-readable summary of the problem type.  It SHOULD NOT change from occurrence to occurrence of the problem, except to match Content-Language',
    )
    status: TinyInt | None = Field(
        default_factory=lambda: TinyInt(0),
        description='The HTTP status code ([RFC7231], Section 6) generated by the origin server for this occurrence of the problem.',
    )
    detail: LongString | None = Field(
        None,
        description='A human-readable explanation specific to this occurrence of the problem, matches Content-Language',
    )
    instance: Url | None = Field(
        None,
        description='A URI reference that identifies the specific occurrence of the problem.  It may or may not yield further information if dereferenced.',
    )
    links: list[Link] | None = None


class LandingPage(BaseModel):
    title: str | None = Field(None, examples=['Example processing server'])
    description: str | None = Field(
        None,
        examples=['Example server implementing the OGC API - Processes 1.0 Standard'],
    )
    attribution: str | None = Field(
        None,
        description='The `attribution` should be short and intended for presentation to a user, for example, in a corner of a map. Parts of the text can be links to other resources if additional information is needed. The string can include HTML markup.',
        title='attribution for the Processes API',
    )
    links: list[Link]


class CollectionInfo(BaseModel):
    id: str = Field(
        ...,
        description='identifier of the collection used, for example, in URIs',
        examples=['dem'],
    )
    title: str | None = Field(
        None,
        description='human readable title of the collection',
        examples=['Digital Elevation Model'],
    )
    description: str | None = Field(
        None,
        description='a description of the data in the collection',
        examples=['A Digital Elevation Model.'],
    )
    links: list[Link]
    extent: dict[str, Any] | None = None
    itemType: str | None = Field(
        'unknown',
        description='indicator about the type of the items in the collection if the collection has an accessible /collections/{collectionId}/items endpoint',
    )
    crs: list[str] | None = Field(
        ['http://www.opengis.net/def/crs/OGC/1.3/CRS84'],
        description='the list of coordinate reference systems supported by the API; the first item is the default coordinate reference system',
        examples=[
            [
                'http://www.opengis.net/def/crs/OGC/1.3/CRS84',
                'http://www.opengis.net/def/crs/EPSG/0/4326',
            ]
        ],
    )
    dataType: DataType | None = None
    geometryDimension: conint(ge=0, le=3) | None = Field(
        None,
        description='The geometry dimension of the features shown in this layer (0: points, 1: curves, 2: surfaces, 3: solids), unspecified: mixed or unknown',
    )
    minScaleDenominator: float | None = Field(
        None, description='Minimum scale denominator for usage of the collection'
    )
    maxScaleDenominator: float | None = Field(
        None, description='Maximum scale denominator for usage of the collection'
    )
    minCellSize: float | None = Field(
        None, description='Minimum cell size for usage of the collection'
    )
    maxCellSize: float | None = Field(
        None, description='Maximum cell size for usage of the collection'
    )


class Metadata1(Link):
    role: str | None = None


class Metadata(RootModel[Metadata1 | Metadata2]):
    root: Metadata1 | Metadata2


class Specification(TravelSpecification, PlaceDefinitions):
    pass


class GeojsonFeature(BaseModel):
    type: constr(pattern=r'^(Feature)$')
    geometry: (
        GeojsonPoint | GeojsonLine | GeojsonPolygon | GeojsonMultiPolygon | None
    ) = None
    properties: Asset | Seat
    id: ShortString
    links: list[Link] | None = None


class Geojson(BaseModel):
    type: constr(pattern=r'^(FeatureCollection)$') | None = None
    features: list[GeojsonFeature] | None = None
    properties: dict[str, Any] | None = None
    crs: Crs | None = None
    numberMatched: int | None = None
    numberReturned: int | None = None
    links: list[Link] | None = Field(
        None,
        description='actions that can be performed on this package, but also alternative (rel=alternative+1, alternative+2) offers or references to other resources In case it is an alternative, specify clearly in the description what the financial consequences are.',
    )


class Leg(TravelSpecification):
    id: LegReference = Field(
        ...,
        description='The unique identifier (TO) of this leg. Must always the same as applied in the request URL. And when there are not additional legs in the offered or purchased package, the same **id** as the package id.',
    )
    type: constr(pattern=r'^(leg)$')
    sequenceNumber: ShortInt | None = Field(
        default_factory=lambda: ShortInt(0),
        description='The order of the leg within the package. Mandatory, if there are multiple legs in the package. If there are parallel legs (eg. using parking lot and a renting a bike), it can be the same within one package.',
    )
    traveller: TravellerReference | None = None
    state: LegState | None = None
    price: AmountOfMoney | None = Field(None, description='the final price of the leg')
    products: list[ShortString] | None = Field(
        None,
        description="a reference to a product in the 'products' collection of the offer",
    )
    ancillaries: list[ShortString] | None = Field(
        None,
        description="additional products that can be assigned to this leg, references to 'ancillaries' collection",
    )
    mode: Mode | None = None
    assets: list[AssetReference] | None = Field(
        None, description='The physical asset(s) used for the execution of the leg'
    )
    operator: OrganisationReference | None = None


class Requirements(BaseModel):
    organisational: list[OrganisationalParameter] | None = None
    spotReservations: list[SpotReservationParameter] | None = None
    distribution: list[DistributionParameter] | None = None
    network: list[NetworkParameter] | None = None
    routing: list[RoutingParameter] | None = None
    service: list[ServiceParameter] | None = None
    temporal: list[TemporalParameter] | None = None
    equipment: list[EquipmentParameter] | None = None
    cancellation: list[CancellationParameter] | None = None
    purchase: list[PurchaseParameter] | None = None


class Card(BaseModel):
    type: constr(pattern=r'^(card)$')
    cardType: CardType | None = None
    cardNumber: ShortString = Field(
        ...,
        description='number of the card, like ID number, credit card or bank account number',
    )
    description: ShortString | None = Field(None, description='description of the card')
    additionalNumber: ShortString | None = Field(
        None, description='additional number, like CVC code or IBAN code'
    )
    endValidity: Date | None = Field(
        None, description='this card is valid until this date'
    )
    country: Country | None = None


class Ancillary1(BaseModel):
    id: NormalString | None = None
    properties: Ancillary | None = None
    links: list[Link] | None = None


class AncillaryCollection(BaseModel):
    type: constr(pattern=r'^(AncillaryCollection)$')
    ancillaries: list[Ancillary1] | None = None
    numberMatched: int | None = None
    numberReturned: int | None = None
    links: list[Link] | None = Field(
        None,
        description='actions that can be performed on this package, but also alternative (rel=alternative+1, alternative+2) offers or references to other resources In case it is an alternative, specify clearly in the description what the financial consequences are.',
    )


class ChangeOption(BaseModel):
    type: constr(pattern=r'^(change_option)$') | None = None
    id: str | None = None
    changeType: (
        Literal[
            'REMOVE_TRAVELLER',
            'ADD_TRAVELLER',
            'UPDATE_TRAVELLER',
            'ASSIGN_ASSET',
            'REMOVE_ASSET',
            'ASSIGN_ANCILLARY',
            'REMOVE_ANCILLARY',
            'CANCEL_PACKAGE',
            'UPDATE_VALIDITY',
            'UPDATE_TRAVEL_SPECIFICATION',
        ]
        | None
    ) = None
    consequences: list[FinancialDetail] | None = None


class RefundOption(BaseModel):
    type: constr(pattern=r'^(refund_option)$') | None = None
    id: Uuid | None = None
    packageState: PackageStatus | None = None
    refundType: (
        Literal['PACKAGE_REFUND', 'REMOVE_TRAVELLER', 'REMOVE_ANCILLARY'] | None
    ) = None
    consequences: list[FinancialDetail] | None = None


class Collections(BaseModel):
    links: list[Link]
    timeStamp: AwareDatetime | None = None
    numberMatched: conint(ge=0) | None = Field(None, examples=[1])
    numberReturned: conint(ge=0) | None = Field(None, examples=[1])
    collections: list[CollectionInfo]


class DescriptionType(BaseModel):
    title: str | None = None
    description: str | None = None
    keywords: list[str] | None = None
    metadata: list[Metadata] | None = None


class Properties1(BaseModel):
    legs: list[Leg] | None = None
    ancillaries: list[Ancillary] | None = None
    products: list[Product] | None = None
    price: AmountOfMoney | None = None
    summary: dict[str, Any] | None = None
    guarantees: list[Guarantee] | None = None
    expiryTime: DateTime | None = None


class Offer(BaseModel):
    id: ShortString | None = None
    type: constr(pattern=r'^(offer)$') | None = None
    properties: Properties1 | None = None
    links: list[Link] | None = None


class Entitlements(BaseModel):
    commercialProfiles: list[CommercialProfile] | None = None
    entitlementsGiven: list[EntitlementGiven] | None = None
    cardTypes: list[CardType] | None = None
    cards: list[Card] | None = None
    licenseTypes: list[LicenseType] | None = None
    licenses: list[License] | None = None


class TravelParty(BaseModel):
    type: str | None = None
    entitlements: Entitlements | None = None
    requirements: Requirements | None = None


class UserProfile(TravelParty):
    id: UserProfileReference
    type: constr(pattern=r'^(user_profile)$')
    count: conint(ge=1, le=100) | None = Field(
        1, description='in case of groups, you can specify the number of people here'
    )
    minimumAge: ShortInt | None = Field(default_factory=lambda: ShortInt(0))
    maximumAge: ShortInt | None = Field(default_factory=lambda: ShortInt(0))
    monthDayOnWhichAgeApplies: ShortInt | None = Field(
        default_factory=lambda: ShortInt(0)
    )
    ageGroup: (
        Literal['ANYONE', 'INFANT', 'CHILD', 'YOUTH', 'ADULT', 'SENIOR'] | None
    ) = None
    minimumHeight: ShortInt | None = Field(default_factory=lambda: ShortInt(0))
    maximumHeight: ShortInt | None = Field(default_factory=lambda: ShortInt(0))
    localResident: bool | None = None
    genderLimitation: bool | None = None


class Option(BaseModel):
    id: NormalString | None = None
    properties: ChangeOption | None = None
    links: list[Link] | None = None


class ChangeOptionCollection(BaseModel):
    type: constr(pattern=r'^(ChangeOptionCollection)$')
    options: list[Option] | None = None
    numberMatched: int | None = None
    numberReturned: int | None = None
    links: list[Link] | None = Field(
        None, description='actions that can be performed on this collection'
    )


class Option1(BaseModel):
    id: NormalString | None = None
    properties: RefundOption | None = None
    links: list[Link] | None = None


class RefundOptionCollection(BaseModel):
    type: constr(pattern=r'^(RefundOptionCollection)$')
    options: list[Option1] | None = None
    numberMatched: int | None = None
    numberReturned: int | None = None
    links: list[Link] | None = Field(
        None,
        description='actions that can be performed on this package, but also alternative (rel=alternative+1, alternative+2) offers or references to other resources In case it is an alternative, specify clearly in the description what the financial consequences are.',
    )


class ProcessSummary(DescriptionType):
    id: str
    version: str
    jobControlOptions: list[JobControlOptions] | None = None
    links: list[Link] | None = None


class OfferCollection(BaseModel):
    type: constr(pattern=r'^(OfferCollection)$')
    offers: list[Offer] | None = None
    numberMatched: int | None = None
    numberReturned: int | None = None
    links: list[Link] | None = Field(
        None,
        description='actions that can be performed on this package, but also alternative (rel=alternative+1, alternative+2) offers or references to other resources In case it is an alternative, specify clearly in the description what the financial consequences are.',
    )


class IndividualTraveller(TravelParty):
    id: TravellerReference
    type: constr(pattern=r'^(individual_traveller)$')
    isValidated: bool | None = Field(
        None,
        description="Whether this traveler's identity and properties have been verified by the MaaS provider",
    )
    age: ShortInt | None = Field(
        default_factory=lambda: ShortInt(0),
        description='Age of the traveler, may be approximate',
    )
    gender: Literal['M', 'F', 'X', 'U'] | None = None
    fullName: NormalString | None = Field(
        None,
        description='the name of the traveller, can be used to validate against ID cards',
    )
    customerReference: CustomerReference | None = None
    customFields: CustomProperties | None = None


class ProcessList(BaseModel):
    processes: list[ProcessSummary]
    links: list[Link]


class SearchOfferInput1(BaseModel):
    type: constr(pattern=r'^(search_offer)')
    timestamp: DateTime | None = Field(None, description='timestamp of request')
    specification: Specification | None = None
    pattern: TripPattern | None = None
    packageToExchange: PackageReference | None = None
    travellers: list[IndividualTraveller] = Field(..., max_length=10, min_length=1)
    profiles: list[UserProfile] | None = Field(None, min_length=1)
    travellingAssets: list[TravellingAsset] | None = Field(None, min_length=1)


class SearchOfferInput2(BaseModel):
    type: constr(pattern=r'^(search_offer)')
    timestamp: DateTime | None = Field(None, description='timestamp of request')
    specification: Specification | None = None
    pattern: TripPattern | None = None
    packageToExchange: PackageReference | None = None
    travellers: list[IndividualTraveller] | None = Field(
        None, max_length=10, min_length=1
    )
    profiles: list[UserProfile] = Field(..., min_length=1)
    travellingAssets: list[TravellingAsset] | None = Field(None, min_length=1)


class SearchOfferInput3(BaseModel):
    type: constr(pattern=r'^(search_offer)')
    timestamp: DateTime | None = Field(None, description='timestamp of request')
    specification: Specification | None = None
    pattern: TripPattern | None = None
    packageToExchange: PackageReference | None = None
    travellers: list[IndividualTraveller] | None = Field(
        None, max_length=10, min_length=1
    )
    profiles: list[UserProfile] | None = Field(None, min_length=1)
    travellingAssets: list[TravellingAsset] = Field(..., min_length=1)


class SearchOfferInput(
    RootModel[SearchOfferInput1 | SearchOfferInput2 | SearchOfferInput3]
):
    root: SearchOfferInput1 | SearchOfferInput2 | SearchOfferInput3 = Field(
        ..., description='A package planning request, resulting in package options'
    )


class AddTravellerInput(BaseModel):
    type: constr(pattern=r'^(traveller)$')
    packageId: PackageReference
    individualTraveller: IndividualTraveller | None = None
    userProfile: UserProfile | None = None
    travellingAsset: TravellingAsset | None = None


class UpdateTravellerInput(BaseModel):
    type: constr(pattern=r'^(traveller)$')
    packageId: PackageReference
    travellerId: TravellerReference
    individualTraveller: IndividualTraveller | None = None
    userProfile: UserProfile | None = None
    travellingAsset: TravellingAsset | None = None


class Package(TravelSpecification, PlaceDefinitions):
    type: constr(pattern=r'^(package)$')
    id: str | None = None
    status: PackageStatus
    price: AmountOfMoney
    offers: list[Offer]
    guarantees: list[ExternalReference] | None = None
    travellers: list[IndividualTraveller | UserProfile | TravellingAsset] | None = None
    links: list[Link] | None = None


class PackageCollection(BaseModel):
    type: Literal['PackageCollection']
    packages: list[Package]
    numberMatched: int | None = Field(
        None, description='Total number of packages available (for pagination)'
    )
    numberReturned: int | None = Field(
        None, description='Number of packages in this response'
    )
    links: list[Link] | None = Field(
        None, description='Actions that can be performed on this collection.'
    )
